---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible==2.7.10
  - pip install molecule
  - pip install docker-py
before_script:
# Use role name for the project directory.
  - cd ../
  - mv ansible-thumbor thumbor
  - cd thumbor
script:
  - molecule test
