---
# Configures thumbor and dependent services
# This task is better run from the Ansible host as it needs a working AWS/Boto setup
# hence using delegate_to localhost
- name: Install Boto3 on the ansible host
  pip:
    name: boto3
    state: present
  delegate_to: 127.0.0.1
  # use normal user on ansible host (avoids switching to root)
  become: false
  when: s3_create_bucket

- name: Create result storage bucket on S3
  aws_s3:
    bucket: "{{ thumbor_result_storage_bucket }}"
    object: "/{{ thumbor_result_storage_path }}"
    mode: create
    region: "{{ s3_aws_region }}"
  # run on ansible host
  delegate_to: 127.0.0.1
  # use normal user on ansible host (avoids switching to root)
  become: false
  when: s3_create_bucket

- name: Create thumbor config directory
  file:
    path: "{{ thumbor_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create thumbor configuration
  template:
    src: thumbor.conf.j2
    dest: "{{ thumbor_config_dir }}/thumbor.conf"
    owner: root
    group: "{{ thumbor_user }}"
    mode: 0640

- name: Ensure thumbor storage dir exists
  file:
    path: "{{ thumbor_storage_path }}"
    state: directory
    owner: "{{ thumbor_user }}"
    group: "{{ thumbor_user }}"
    mode: 0755

- name: Ensure thumbor log dir exists
  file:
    path: "{{ thumbor_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

# Supervisord setup

- name: Ensure supervisord log dir exists
  file:
    path: "{{ supervisord_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '15.04'

- name: Make sure supervisord service is enabled to start on boot (on older Ubuntus)
  service:
    name: supervisor
    enabled: yes
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '15.04'

- name: Setup supervisord config file to starte thumbor processes (on older Ubuntus)
  template:
    src: supervisord.conf.j2
    dest: "/etc/supervisor/supervisord.conf"
  notify:
    - restart supervisor
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '15.04'

# Systemd setup

- name: Setup systemd template config to start Thumbor processes (on newer Ubuntus)
  template:
    src: thumbor.service.j2
    dest: /etc/systemd/system/thumbor@.service
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version >= '15.04'

- name: Setup systemd target to start Thumbor processes (on newer Ubuntus)
  template:
    src: thumbor.target.j2
    dest: /etc/systemd/system/thumbor.target
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version >= '15.04'

- name: Make sure enable on systemd service on boot
  systemd:
    name: thumbor.target
    enabled: yes
    state: restarted
    daemon_reload: yes
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version >= '15.04'
