---
- name: Create thumbor group.
  group:
    name: "{{ thumbor_group }}"

- name: Create thumbor user.
  user:
    name: "{{ thumbor_user }}"
    group: "{{ thumbor_group }}"
    shell: "{{ thumbor_shell }}"
    home: "{{ thumbor_home }}"
    create_home: yes

- name: Ensure system dependencies are installed
  apt:
    pkg: "{{ thumbor_system_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Symbolic link for libboost_python3
  file:
    src: "/usr/lib/x86_64-linux-gnu/libboost_python38.a"
    dest: "/usr/lib/x86_64-linux-gnu/libboost_python3.a"
    state: link

- name: Symbolic link for libboost_python3
  file:
    src: "/usr/lib/x86_64-linux-gnu/libboost_python38.so"
    dest: "/usr/lib/x86_64-linux-gnu/libboost_python3.so"
    state: link

- name: Install virtualenv via pip
  pip:
    name: "virtualenv"
    virtualenv_python:  "{{ thumbor_python_executable }}"

- name: Delete the Thumbor virtualenv directory
  file:
    state: absent
    path: "{{ thumbor_virtualenv_path }}"
  when: thumbor_recreate_virtualenv

- name: Install thumbor from pypi
  become: true
  become_user: "{{ thumbor_user }}"
  pip:
    name: "thumbor[all]"
    version: "{{ thumbor_version }}"
    virtualenv: "{{ thumbor_virtualenv_path }}"
    virtualenv_python: "{{ thumbor_python_executable }}"

- name: Install thumbor AWS plugin from pypi
  become: true
  become_user: "{{ thumbor_user }}"
  pip:
    name: tc_aws
    version: "{{ thumbor_aws_plugin_version }}"
    virtualenv: "{{ thumbor_virtualenv_path }}"
    virtualenv_python: "{{ thumbor_python_executable }}"
  when: thumbor_use_aws_storage

- name: Install additional packages
  become: true
  become_user: "{{ thumbor_user }}"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ thumbor_virtualenv_path }}"
    virtualenv_python: "{{ thumbor_python_executable }}"
  with_items: "{{ thumbor_additional_pip_packages }}"
