---
- name: Ensure dependencies are installed
  apt:
    pkg: ["python-setuptools", "python-pip", "python-dev"]
    update_cache: yes

- name: Install virtualenv via pip
  pip:
    name: "virtualenv"
    executable: pip
