---
- name: Converge
  hosts: all
  vars:
    thumbor_signing_key: ABC123def456
    thumbor_s3_create_bucket: false
    ansible_python_interpreter: "/usr/bin/env python2"
  roles:
    - role: thumbor
