---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: ansible
  lint: |
    flake8
